/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./inertia/components/ui/alert/Alert.vue')['default']
    AlertDescription: typeof import('./inertia/components/ui/alert/AlertDescription.vue')['default']
    AlertTitle: typeof import('./inertia/components/ui/alert/AlertTitle.vue')['default']
    AreaChart: typeof import('./inertia/components/ui/chart-area/AreaChart.vue')['default']
    Button: typeof import('./inertia/components/ui/button/Button.vue')['default']
    Card: typeof import('./inertia/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./inertia/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./inertia/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./inertia/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./inertia/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./inertia/components/ui/card/CardTitle.vue')['default']
    ChartCrosshair: typeof import('./inertia/components/ui/chart/ChartCrosshair.vue')['default']
    ChartLegend: typeof import('./inertia/components/ui/chart/ChartLegend.vue')['default']
    ChartSingleTooltip: typeof import('./inertia/components/ui/chart/ChartSingleTooltip.vue')['default']
    ChartTooltip: typeof import('./inertia/components/ui/chart/ChartTooltip.vue')['default']
    Checkbox: typeof import('./inertia/components/ui/checkbox/Checkbox.vue')['default']
    DonutChart: typeof import('./inertia/components/ui/chart-donut/DonutChart.vue')['default']
    DurationChart: typeof import('./inertia/components/DurationChart.vue')['default']
    FormControl: typeof import('./inertia/components/ui/form/FormControl.vue')['default']
    FormDescription: typeof import('./inertia/components/ui/form/FormDescription.vue')['default']
    FormItem: typeof import('./inertia/components/ui/form/FormItem.vue')['default']
    FormLabel: typeof import('./inertia/components/ui/form/FormLabel.vue')['default']
    FormMessage: typeof import('./inertia/components/ui/form/FormMessage.vue')['default']
    Input: typeof import('./inertia/components/ui/input/Input.vue')['default']
    Label: typeof import('./inertia/components/ui/label/Label.vue')['default']
    SalesChart: typeof import('./inertia/components/SalesChart.vue')['default']
    Sidebar: typeof import('./inertia/components/Sidebar.vue')['default']
    Sonner: typeof import('./inertia/components/ui/sonner/Sonner.vue')['default']
    Stats: typeof import('./inertia/components/Stats.vue')['default']
    Toasts: typeof import('./inertia/components/Toasts.vue')['default']
    TodayActivity: typeof import('./inertia/components/TodayActivity.vue')['default']
  }
}
