/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./inertia/components/ui/alert/Alert.vue')['default']
    AlertDescription: typeof import('./inertia/components/ui/alert/AlertDescription.vue')['default']
    AlertTitle: typeof import('./inertia/components/ui/alert/AlertTitle.vue')['default']
    Button: typeof import('./inertia/components/ui/button/Button.vue')['default']
    Checkbox: typeof import('./inertia/components/ui/checkbox/Checkbox.vue')['default']
    FormControl: typeof import('./inertia/components/ui/form/FormControl.vue')['default']
    FormDescription: typeof import('./inertia/components/ui/form/FormDescription.vue')['default']
    FormItem: typeof import('./inertia/components/ui/form/FormItem.vue')['default']
    FormLabel: typeof import('./inertia/components/ui/form/FormLabel.vue')['default']
    FormMessage: typeof import('./inertia/components/ui/form/FormMessage.vue')['default']
    Input: typeof import('./inertia/components/ui/input/Input.vue')['default']
    Label: typeof import('./inertia/components/ui/label/Label.vue')['default']
  }
}
